# 1.创建操作

| 操作类型           | 语法                              | 解释                                                                 |
|--------------------|-----------------------------------|----------------------------------------------------------------------|
| `np.array()`       | `np.array([[1, 2, 3], [4, 5, 6]])` | 从列表或嵌套列表创建数组                                             |
| `np.zeros()`       | `np.zeros((2, 3))`                | 创建指定形状的全 0 数组（2 行 3 列）                                 |
| `np.ones()`        | `np.ones((2, 3))`                 | 创建指定形状的全 1 数组（2 行 3 列）                                 |
| `np.arange()`      | `np.arange(0, 10, 2)`             | 创建从 0 到 10（不包含 10），步长为 2 的数组                          |
| `np.linspace()`    | `np.linspace(0, 10, 5)`           | 创建从 0 到 10（包含 10），均匀分布的 5 个数的数组                    |

In [1]:
import numpy as np

# 创建一个数组，当然也可以在excel等程序中直接导入
arr = np.array([[1, 2, 3, 4, 5],
               [2, 2, 3, 4, 5],
               [3, 2, 3, 4, 5],
               [4, 2, 3, 4, 5],
               [5, 2, 3, 4, 5],
               [6, 2, 3, 4, 5],
               [7, 2, 3, 4, 5],
               [8, 2, 3, 4, 5],
               [9, 2, 3, 4, 5]])

# 创建数组
arr_zero = np.zeros((2, 3))           # 2x3 的0矩阵
print("zeros:\n", arr_zero)
arr_one = np.ones((2, 3))             # 2x3 的单位阵
print("ones:\n", arr_one)
arr_range = np.arange(0, 10, 2)       # 从 0 到 10，步长为 2
print("arange:", arr_range)
arr_linspace = np.linspace(0, 10, 5)  # 从 0 到 10 之间均匀分布的 5 个数
print("linspace:", arr_linspace)
print("================创建数组================")

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [ 0.   2.5  5.   7.5 10. ]
================创建数组================


| 操作类型   | 语法                     | 解释                                                                 |
|------------|--------------------------|----------------------------------------------------------------------|
| ​**数组属性** |                          |                                                                      |
| `ndarray`  | `np.array([1, 2, 3])`    | NumPy 的核心数据结构，表示一个多维数组                                |
| `dtype`    | `arr.dtype`              | 返回数组 `arr` 元素的类型                                            |
| `ndim`     | `arr.ndim`               | 返回数组 `arr` 的维度数                                              |
| `shape`    | `arr.shape`              | 返回数组 `arr` 的形状（各维度的大小）                                |
| `size`     | `arr.size`               | 返回数组 `arr` 元素总数                                              |
| `itemsize` | `arr.itemsize`           | 返回数组 `arr` 中每个元素的字节大小                                  |
| ​**数组方法** |                          |                                                                      |
| `reshape()`| `arr.reshape(2, 3)`      | 改变数组 `arr` 的形状（不改变数据）                                  |
| `flatten()`| `arr.flatten()`          | 将多维数组 `arr` 展平为一维数组（返回副本）                          |
| `ravel()`  | `arr.ravel()`            | 返回数组 `arr` 展平后的视图（返回原数据）                            |
| `transpose()`| `arr.transpose()`      | 对数组 `arr` 进行转置                                                |

# 2.读取

In [2]:
import numpy as np
import pandas as pd

path = r'../iris.data'
headers = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv(path, header=None, names=headers)
df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
# 将 DataFrame 转换为 NumPy 数组
arr = df.to_numpy()  # 或者 data = df.values
print("ndarray:", arr)               # NumPy 核心数据结构

ndarray: [[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 

In [4]:
# 数组属性
print("dtype:", arr.dtype)           # 元素类型
print("ndim:", arr.ndim)             # 数组维度数
print("shape:", arr.shape)           # 数组形状
print("size:", arr.size)             # 数组元素总数
print("itemsize:", arr.itemsize)     # 每个元素字节大小
print('==============数组属性====================')


dtype: object
ndim: 2
shape: (150, 5)
size: 750
itemsize: 8
==============数组属性====================


In [5]:
# 数组方法
reshaped = arr.reshape(5,150)         # 改变形状,必须跟原形状一致，比如原形状shape: (150, 5)=150X5=750;那么无论如何变形结果必须也是750
reshaped

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 4.9, 3.0, 1.4, 0.2,
        'Iris-setosa', 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 4.6, 3.1, 1.5,
        0.2, 'Iris-setosa', 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 5.4, 3.9,
        1.7, 0.4, 'Iris-setosa', 4.6, 3.4, 1.4, 0.3, 'Iris-setosa', 5.0,
        3.4, 1.5, 0.2, 'Iris-setosa', 4.4, 2.9, 1.4, 0.2, 'Iris-setosa',
        4.9, 3.1, 1.5, 0.1, 'Iris-setosa', 5.4, 3.7, 1.5, 0.2,
        'Iris-setosa', 4.8, 3.4, 1.6, 0.2, 'Iris-setosa', 4.8, 3.0, 1.4,
        0.1, 'Iris-setosa', 4.3, 3.0, 1.1, 0.1, 'Iris-setosa', 5.8, 4.0,
        1.2, 0.2, 'Iris-setosa', 5.7, 4.4, 1.5, 0.4, 'Iris-setosa', 5.4,
        3.9, 1.3, 0.4, 'Iris-setosa', 5.1, 3.5, 1.4, 0.3, 'Iris-setosa',
        5.7, 3.8, 1.7, 0.3, 'Iris-setosa', 5.1, 3.8, 1.5, 0.3,
        'Iris-setosa', 5.4, 3.4, 1.7, 0.2, 'Iris-setosa', 5.1, 3.7, 1.5,
        0.4, 'Iris-setosa', 4.6, 3.6, 1.0, 0.2, 'Iris-setosa', 5.1, 3.3,
        1.7, 0.5, 'Iris-setosa', 4.8, 3.4, 1.9, 0.2, 'Iris-setosa', 5.0,
        

In [6]:
flattened = arr.flatten()            # 展平为一维数组
flattened

array([5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 4.9, 3.0, 1.4, 0.2,
       'Iris-setosa', 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 4.6, 3.1, 1.5,
       0.2, 'Iris-setosa', 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 5.4, 3.9,
       1.7, 0.4, 'Iris-setosa', 4.6, 3.4, 1.4, 0.3, 'Iris-setosa', 5.0,
       3.4, 1.5, 0.2, 'Iris-setosa', 4.4, 2.9, 1.4, 0.2, 'Iris-setosa',
       4.9, 3.1, 1.5, 0.1, 'Iris-setosa', 5.4, 3.7, 1.5, 0.2,
       'Iris-setosa', 4.8, 3.4, 1.6, 0.2, 'Iris-setosa', 4.8, 3.0, 1.4,
       0.1, 'Iris-setosa', 4.3, 3.0, 1.1, 0.1, 'Iris-setosa', 5.8, 4.0,
       1.2, 0.2, 'Iris-setosa', 5.7, 4.4, 1.5, 0.4, 'Iris-setosa', 5.4,
       3.9, 1.3, 0.4, 'Iris-setosa', 5.1, 3.5, 1.4, 0.3, 'Iris-setosa',
       5.7, 3.8, 1.7, 0.3, 'Iris-setosa', 5.1, 3.8, 1.5, 0.3,
       'Iris-setosa', 5.4, 3.4, 1.7, 0.2, 'Iris-setosa', 5.1, 3.7, 1.5,
       0.4, 'Iris-setosa', 4.6, 3.6, 1.0, 0.2, 'Iris-setosa', 5.1, 3.3,
       1.7, 0.5, 'Iris-setosa', 4.8, 3.4, 1.9, 0.2, 'Iris-setosa', 5.0,
       3.0, 1.6, 0.2, 

In [7]:
raveled = arr.ravel()                # 展平视图
raveled

array([5.1, 3.5, 1.4, 0.2, 'Iris-setosa', 4.9, 3.0, 1.4, 0.2,
       'Iris-setosa', 4.7, 3.2, 1.3, 0.2, 'Iris-setosa', 4.6, 3.1, 1.5,
       0.2, 'Iris-setosa', 5.0, 3.6, 1.4, 0.2, 'Iris-setosa', 5.4, 3.9,
       1.7, 0.4, 'Iris-setosa', 4.6, 3.4, 1.4, 0.3, 'Iris-setosa', 5.0,
       3.4, 1.5, 0.2, 'Iris-setosa', 4.4, 2.9, 1.4, 0.2, 'Iris-setosa',
       4.9, 3.1, 1.5, 0.1, 'Iris-setosa', 5.4, 3.7, 1.5, 0.2,
       'Iris-setosa', 4.8, 3.4, 1.6, 0.2, 'Iris-setosa', 4.8, 3.0, 1.4,
       0.1, 'Iris-setosa', 4.3, 3.0, 1.1, 0.1, 'Iris-setosa', 5.8, 4.0,
       1.2, 0.2, 'Iris-setosa', 5.7, 4.4, 1.5, 0.4, 'Iris-setosa', 5.4,
       3.9, 1.3, 0.4, 'Iris-setosa', 5.1, 3.5, 1.4, 0.3, 'Iris-setosa',
       5.7, 3.8, 1.7, 0.3, 'Iris-setosa', 5.1, 3.8, 1.5, 0.3,
       'Iris-setosa', 5.4, 3.4, 1.7, 0.2, 'Iris-setosa', 5.1, 3.7, 1.5,
       0.4, 'Iris-setosa', 4.6, 3.6, 1.0, 0.2, 'Iris-setosa', 5.1, 3.3,
       1.7, 0.5, 'Iris-setosa', 4.8, 3.4, 1.9, 0.2, 'Iris-setosa', 5.0,
       3.0, 1.6, 0.2, 

In [8]:
transposed = reshaped.transpose()    # 转置
transposed

array([[5.1, 4.8, 5.0, 5.5, 6.9],
       [3.5, 3.1, 2.0, 2.6, 3.2],
       [1.4, 1.6, 3.5, 4.4, 5.7],
       [0.2, 0.2, 1.0, 1.2, 2.3],
       ['Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-virginica'],
       [4.9, 5.4, 5.9, 6.1, 5.6],
       [3.0, 3.4, 3.0, 3.0, 2.8],
       [1.4, 1.5, 4.2, 4.6, 4.9],
       [0.2, 0.4, 1.5, 1.4, 2.0],
       ['Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-virginica'],
       [4.7, 5.2, 6.0, 5.8, 7.7],
       [3.2, 4.1, 2.2, 2.6, 2.8],
       [1.3, 1.5, 4.0, 4.0, 6.7],
       [0.2, 0.1, 1.0, 1.2, 2.0],
       ['Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-virginica'],
       [4.6, 5.5, 6.1, 5.0, 6.3],
       [3.1, 4.2, 2.9, 2.3, 2.7],
       [1.5, 1.4, 4.7, 3.3, 4.9],
       [0.2, 0.2, 1.4, 1.0, 1.8],
       ['Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-virginica'],
       [5.0, 4.9, 5.6, 5.6, 6.7],
       [3.

# 3.增、删、改、查操作

| 操作类型 | 语法                             | 解释                                                                 |
|----------|----------------------------------|----------------------------------------------------------------------|
| ​**创建** |                                  |                                                                      |
|          | `np.array([1, 2, 3])`            | 创建一个一维数组，元素为列表中的值                                   |
|          | `np.zeros((2, 3))`              | 创建一个 2x3 的 0 矩阵                                               |
|          | `np.ones((2, 3))`                | 创建一个 2x3 的单位阵                                               |
|          | `np.arange(0, 10, 2)`            | 创建一个元素为从 0 到 9（不包括 10）的连续数，步长为 2 的数组         |
|          | `np.linspace(0, 10, 5)`          | 创建一个数组，元素为从 0 到 10 之间均匀分布的 5 个数                 |
| ​**增**   |                                  |                                                                      |
|          | `np.append(arr, [4, 5])`         | 向数组 `arr` 末尾添加元素 `[4, 5]`                                   |
|          | `np.insert(arr, 1, 10)`          | 在数组 `arr` 的索引位置 1 处插入值 10                                |
| ​**删**   |                                  |                                                                      |
|          | `np.delete(arr, 2)`              | 删除数组 `arr` 中索引位置为 2 的元素                                |
| ​**改**   |                                  |                                                                      |
|          | `arr[0] = 10`                    | 将数组 `arr` 中索引为 0 的元素覆盖改为 10                           |
| ​**查**   |                                  |                                                                      |
|          | `arr[0]`                         | 访问数组 `arr` 中索引为 0 的元素                                    |
|          | `arr[0:11:2]`                    | 访问数组 `arr` 中索引为 0 到 11（不包括 11）步长 2 的子数组         |
|          | `arr[arr > 3]`                   | 查找数组 `arr` 中大于 3 的元素                                      |
|          | `arr[-1]`                        | 从数组倒数第一个访问元素                                            |
|          | `np.where(arr > 2, arr, 0)`      | 满足条件的元素保留，其余元素替换为 0                                |
|          | `np.argmax(arr)`                 | 查找最大值的索引位置                                                |
|          | `np.argmin(arr)`                 | 查找最小值的索引位置                                                |
|          | `np.take(arr, [0, 2, 4])`        | 将数据变为一维数据，然后选取特定索引位置的元素                      |
|          | `arr[:, 1]`                      | 传入行列两个数据，`:` 表示所有；代码表示所有行，索引第 1 列         |

In [9]:
import numpy as np

# 创建一个数组
arr = np.array([[1, 2, 3, 4, 5],
               [2, 2, 3, 4, 5],
               [3, 2, 3, 4, 5],
               [4, 2, 3, 4, 5],
               [5, 2, 3, 4, 5],
               [6, 2, 3, 4, 5],
               [7, 2, 3, 4, 5],
               [8, 2, 3, 4, 5],
               [9, 2, 3, 4, 5]])
arr


array([[1, 2, 3, 4, 5],
       [2, 2, 3, 4, 5],
       [3, 2, 3, 4, 5],
       [4, 2, 3, 4, 5],
       [5, 2, 3, 4, 5],
       [6, 2, 3, 4, 5],
       [7, 2, 3, 4, 5],
       [8, 2, 3, 4, 5],
       [9, 2, 3, 4, 5]])

## 3.1 增

In [10]:
# 增
print("================增================")
arr_append = np.append(arr, [6, 7, 8, 9, 10])       # 向末尾添加元素,会变成一维数组
print("append:\n", arr_append)
arr_insert = np.insert(arr, 1, 10)       # 在索引 1 处插入值 10,会变成一维数组
print("insert:\n", arr_insert)
print("reshape:\n")
arr_append = arr_append.reshape(-1, 5) # 变成二维数组,这里-1表示自动计算行数
arr_append

================增================
append:
 [ 1  2  3  4  5  2  2  3  4  5  3  2  3  4  5  4  2  3  4  5  5  2  3  4
  5  6  2  3  4  5  7  2  3  4  5  8  2  3  4  5  9  2  3  4  5  6  7  8
  9 10]
insert:
 [ 1 10  2  3  4  5  2  2  3  4  5  3  2  3  4  5  4  2  3  4  5  5  2  3
  4  5  6  2  3  4  5  7  2  3  4  5  8  2  3  4  5  9  2  3  4  5]
reshape:



array([[ 1,  2,  3,  4,  5],
       [ 2,  2,  3,  4,  5],
       [ 3,  2,  3,  4,  5],
       [ 4,  2,  3,  4,  5],
       [ 5,  2,  3,  4,  5],
       [ 6,  2,  3,  4,  5],
       [ 7,  2,  3,  4,  5],
       [ 8,  2,  3,  4,  5],
       [ 9,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# 删
arr_delete = np.delete(arr, 2)           # 删除索引为 2 的元素
print("delete:\n", arr_delete)
print("================删================")


delete:
 [1 2 4 5 2 2 3 4 5 3 2 3 4 5 4 2 3 4 5 5 2 3 4 5 6 2 3 4 5 7 2 3 4 5 8 2 3
 4 5 9 2 3 4 5]
================删================


In [12]:
# 改
arr[0] = 10                               # 将索引为 0 的元素修改为 10
print("modified arr:\n", arr)
print("================改================")


modified arr:
 [[10 10 10 10 10]
 [ 2  2  3  4  5]
 [ 3  2  3  4  5]
 [ 4  2  3  4  5]
 [ 5  2  3  4  5]
 [ 6  2  3  4  5]
 [ 7  2  3  4  5]
 [ 8  2  3  4  5]
 [ 9  2  3  4  5]]
================改================


In [13]:
# 查
print('原始数组:\n', arr)
print("access index 0:\n", arr[0])         # 访问索引为 0 的元素
print("slice [0:8:2]:\n", arr[0:8:2])    # 索引为 0 到 7（步长 2）的子数组
print("elements > 3:\n", arr[arr > 3])     # 查找大于 3 的元素
print("last element:\n", arr[-1])          # 访问倒数第一个元素


原始数组:
 [[10 10 10 10 10]
 [ 2  2  3  4  5]
 [ 3  2  3  4  5]
 [ 4  2  3  4  5]
 [ 5  2  3  4  5]
 [ 6  2  3  4  5]
 [ 7  2  3  4  5]
 [ 8  2  3  4  5]
 [ 9  2  3  4  5]]
access index 0:
 [10 10 10 10 10]
slice [0:8:2]:
 [[10 10 10 10 10]
 [ 3  2  3  4  5]
 [ 5  2  3  4  5]
 [ 7  2  3  4  5]]
elements > 3:
 [10 10 10 10 10  4  5  4  5  4  4  5  5  4  5  6  4  5  7  4  5  8  4  5
  9  4  5]
last element:
 [9 2 3 4 5]


In [14]:
# np.where
arr_condition = np.where(arr > 2, arr, 0)  # 满足条件的保留，其余替换为 0
print("where condition:\n", arr_condition)

# np.argmax, np.argmin
print("argmax (index of max value):\n", np.argmax(arr)) # 返回最大值索引
print("argmin (index of min value):\n", np.argmin(arr)) # 返回最小值索引

# np.take
arr_take = np.take(arr, [0, 2, 4])        # 选择特定索引位置的元素，展开为一维进行索引取值
print("take:\n", arr_take)

# 获取特定列
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 二维数组
print("second column:\n", arr_2d[:, 1])  # 所有行，获取第二列
print("================查================")


where condition:
 [[10 10 10 10 10]
 [ 0  0  3  4  5]
 [ 3  0  3  4  5]
 [ 4  0  3  4  5]
 [ 5  0  3  4  5]
 [ 6  0  3  4  5]
 [ 7  0  3  4  5]
 [ 8  0  3  4  5]
 [ 9  0  3  4  5]]
argmax (index of max value):
 0
argmin (index of min value):
 5
take:
 [10 10 10]
second column:
 [2 5 8]
================查================
