| 操作            | 示例                            | 说明                                                                 |
|-----------------|---------------------------------|----------------------------------------------------------------------|
| ​**矩阵加法**    | `np.add(arr1, arr2)`            | 对两个数组进行逐元素相加                                             |
| ​**矩阵减法**    | `np.subtract(arr1, arr2)`       | 对两个数组进行逐元素相减                                             |
| ​**矩阵乘法**    | `np.dot(arr1, arr2)`            | 进行矩阵乘法                                                         |
| ​**矩阵除法**    | `np.divide(arr1, arr2)`         | 对两个数组进行逐元素除法                                             |
| ​**元素乘法**    | `arr1 * arr2`                   | 对两个数组进行逐元素相乘                                             |
| ​**元素除法**    | `arr1 / arr2`                   | 对两个数组进行逐元素除法                                             |
| ​**转置**        | `np.transpose(arr)`             | 对矩阵进行转置操作                                                   |
| ​**求和**        | `np.sum(arr)`                   | 计算数组的所有元素的和                                               |
| ​**求列和**      | `np.sum(arr, axis=0)`           | 计算每列的和，`axis=0`                                               |
| ​**求行和**      | `np.sum(arr, axis=1)`           | 计算每行的和，`axis=1`                                               |
| ​**均值**        | `np.mean(arr)`                  | 计算数组的均值                                                       |
| ​**行均值**      | `np.mean(arr, axis=1)`          | 计算每行的均值                                                       |
| ​**列均值**      | `np.mean(arr, axis=0)`          | 计算每列的均值                                                       |
| ​**中位数**      | `np.median(arr)`                | 计算数组的中位数                                                     |
| ​**最大值**      | `np.max(arr)`                   | 计算数组的最大值                                                     |
| ​**最小值**      | `np.min(arr)`                   | 计算数组的最小值                                                     |
| ​**最大值索引**  | `np.argmax(arr)`                | 计算数组中最大值的位置索引                                           |
| ​**最小值索引**  | `np.argmin(arr)`                | 计算数组中最小值的位置索引                                           |
| ​**标准差**      | `np.std(arr)`                   | 计算数组的标准差                                                     |
| ​**方差**        | `np.var(arr)`                   | 计算数组的方差                                                       |
| ​**矩阵行列式**  | `np.linalg.det(arr)`            | 计算矩阵的行列式（仅适用于方阵）                                     |
| ​**矩阵逆**      | `np.linalg.inv(arr)`            | 计算矩阵的逆（仅适用于非奇异方阵）                                   |
| ​**分组计算**    | `np.groupby(arr, key)`          | 按照给定的分组键计算分组后，可以计算每组的统计量                     |
| ​**应用函数**    | `np.apply_along_axis(func, axis, arr)` | 沿着指定轴应用函数                                           |
| ​**广播**        | `arr1 + arr2`                   | 不同形状的数组也可以进行运算，前提是它们能够通过广播规则对齐         |

In [1]:
import numpy as np

# 创建示例数组
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]


In [2]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 矩阵加法
add_result = np.add(arr1, arr2)
print("矩阵加法:\n", add_result)


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
矩阵加法:
 [[ 6  8]
 [10 12]]


In [3]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 矩阵减法
subtract_result = np.subtract(arr1, arr2)
print("矩阵减法:\n", subtract_result)


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
矩阵减法:
 [[-4 -4]
 [-4 -4]]


In [4]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 矩阵乘法
dot_result = np.dot(arr1, arr2) # 广播机制
print("矩阵乘法:\n", dot_result)


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
矩阵乘法:
 [[19 22]
 [43 50]]


In [5]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 元素乘法
elementwise_mul = arr1 * arr2 # 点乘
print("元素乘法:\n", elementwise_mul)


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
元素乘法:
 [[ 5 12]
 [21 32]]


In [6]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 矩阵除法
divide_result = np.divide(arr1, arr2) # 点除
print("矩阵除法:\n", divide_result)


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
矩阵除法:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [7]:
print("arr1:\n", arr1)
print("arr2:\n", arr2)
# 元素除法
elementwise_div = arr1 / arr2
print("元素除法:\n", elementwise_div) # 点除


arr1:
 [[1 2]
 [3 4]]
arr2:
 [[5 6]
 [7 8]]
元素除法:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
print("arr1:\n", arr1)
# 转置
transpose_result = np.transpose(arr1)
print("转置:\n", transpose_result)


arr1:
 [[1 2]
 [3 4]]
转置:
 [[1 3]
 [2 4]]


In [9]:
print("arr1:\n", arr1)
# 求和
sum_result = np.sum(arr1)
print("求和:", sum_result)


arr1:
 [[1 2]
 [3 4]]
求和: 10


In [10]:
print("arr1:\n", arr1)
# 求列和
sum_col = np.sum(arr1, axis=0)
print("求列和:", sum_col)


arr1:
 [[1 2]
 [3 4]]
求列和: [4 6]


In [11]:
print("arr1:\n", arr1)
# 求行和
sum_row = np.sum(arr1, axis=1)
print("求行和:", sum_row)


arr1:
 [[1 2]
 [3 4]]
求行和: [3 7]


In [12]:
print("arr1:\n", arr1)
# 均值
mean_result = np.mean(arr1)
print("均值:", mean_result)


arr1:
 [[1 2]
 [3 4]]
均值: 2.5


In [13]:
print("arr1:\n", arr1)
# 行均值
mean_row = np.mean(arr1, axis=1)
print("行均值:", mean_row)


arr1:
 [[1 2]
 [3 4]]
行均值: [1.5 3.5]


In [14]:
print("arr1:\n", arr1)
# 列均值
mean_col = np.mean(arr1, axis=0)
print("列均值:", mean_col)


arr1:
 [[1 2]
 [3 4]]
列均值: [2. 3.]


In [15]:
print("arr1:\n", arr1)
# 中位数
median_result = np.median(arr1)
print("中位数:", median_result)


arr1:
 [[1 2]
 [3 4]]
中位数: 2.5


In [16]:
print("arr1:\n", arr1)
# 最大值
max_result = np.max(arr1)
print("最大值:", max_result)


arr1:
 [[1 2]
 [3 4]]
最大值: 4


In [17]:
print("arr1:\n", arr1)
# 最小值
min_result = np.min(arr1)
print("最小值:", min_result)


arr1:
 [[1 2]
 [3 4]]
最小值: 1


In [18]:
print("arr1:\n", arr1)
# 最大值索引
argmax_result = np.argmax(arr1)
print("最大值索引:", argmax_result)


arr1:
 [[1 2]
 [3 4]]
最大值索引: 3


In [19]:
print("arr1:\n", arr1)
# 最小值索引
argmin_result = np.argmin(arr1)
print("最小值索引:", argmin_result)


arr1:
 [[1 2]
 [3 4]]
最小值索引: 0


In [20]:
print("arr1:\n", arr1)
# 标准差
std_result = np.std(arr1)
print("标准差:", std_result)


arr1:
 [[1 2]
 [3 4]]
标准差: 1.118033988749895


In [21]:
print("arr1:\n", arr1)
# 方差
var_result = np.var(arr1)
print("方差:", var_result)


arr1:
 [[1 2]
 [3 4]]
方差: 1.25


In [22]:
print("arr1:\n", arr1)
# 矩阵行列式
det_result = np.linalg.det(arr1)
print("矩阵行列式:", det_result)


arr1:
 [[1 2]
 [3 4]]
矩阵行列式: -2.0000000000000004


In [23]:
print("arr1:\n", arr1)
# 矩阵逆
inv_result = np.linalg.inv(arr1)
print("矩阵逆:\n", inv_result)


arr1:
 [[1 2]
 [3 4]]
矩阵逆:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
print("arr1:\n", arr1)
# 应用函数
def square(x):
    return x ** 2

apply_result = np.apply_along_axis(square, 0, arr1)
print("应用函数（平方）:\n", apply_result)


arr1:
 [[1 2]
 [3 4]]
应用函数（平方）:
 [[ 1  4]
 [ 9 16]]


In [25]:
print("arr1:\n", arr1)
# 广播
arr3 = np.array([1, 2])
broadcast_result = arr1 + arr3
print("广播:\n", broadcast_result)

arr1:
 [[1 2]
 [3 4]]
广播:
 [[2 4]
 [4 6]]
